using LinearAlgebra, SparseArrays, ITensors

c6 = [
    10 5;
    5 10
] # matrix c6{ij} for rydberg interaction coefficient between qudits i,j;
  # diagonals are therefore the intra-, off-diagonals the inter-rydberg coefficients
rydberg_states = size(c6)[1] # no. of rydberg states used
node_locations = [0 0 ; 1 0] # location of the qudits (representing nodes of the graph)
detunings = [-2 -4] # one detuning for each rydberg state
rabis = [2 4] # one rabi frequency for between |g> and |r_i> for each rydberg state
initial_state = [x > 1 ? 0 : x for x in 1:((rydberg_states+1)^size(node_locations)[1])] # ground state, all qudits |0>

id = 1 * Matrix{Float64}(I, rydberg_states+1, rydberg_states+1) # single-qudit identity matrix, dimension |g> + all |r_i>

function hamiltonian(detunings, rabis, c6, node_locations)
    """Generate total Hamiltonian of system using above parameters; sum of drive + interaction Hamiltonians"""
    single = zeros(rydberg_states+1, rydberg_states+1)

    # populate single qubit hamiltonian
    for i in 1:rydberg_states
        single[i+1, i+1] = detunings[i]
        single[1, i+1] = rabis[i]
        single[i+1, 1] = rabis[i]
    end

    # generate placeholder matrix of total dimension of end product hamiltonian
    n_qudits = size(node_locations)[1]
    drive = zeros((rydberg_states+1)^n_qudits, (rydberg_states+1)^n_qudits)

    # tensor product sum of single qubit Hamiltonians
    for i in 1:n_qudits
        left_product = id
        drive_temp = id
        i == 1 ? drive_temp = single : drive_temp = id
        for m in 2:n_qudits
            m == i ? left_product = single : left_product = id
            drive_temp = kron(left_product, drive_temp)
        end
        drive += drive_temp
    end
    
    # placeholder matrix for interaction Hamiltonian
    dim = size(id)[1]^n_qudits
    h_int_total = zeros(dim, dim)

    # tensor product sum for interaction Hamiltonian: for every |r_p, r_q><r_p, r_q|(i,j) coefficient (i.e. matrix element)
    # generates a dim x dim matrix with that coefficient in the correct place; a sum then runs over every p,q (including q,p).
    # This procedure runs over every pair of qudits i,j. Each |r_p, r_q><r_p, r_q|(i,j) coefficient matrix is generated by the
    # square root of the coefficient value in the required location (and zeros elsewhere) replacing the identity matrix in the
    # positions i,j in the tensor product, i.e. I_1 * I_2 * |r_1><r_1|(3) * I_4 * |r_2><r_2|(5) * I_6 is the term in a six-qudit
    # setup for the intra-rydberg interaction between the rydberg states r_1 and r_2 between qudits 3 and 5; note there must
    # also be an additional term with r_1 and r_2 switched between the same qudits for these two rydberg states.
    for p in 1:rydberg_states
        for q in 1:rydberg_states
            for i in 1:n_qudits
                for j in i+1:n_qudits
                    h_int_temp = id
                    left_product = id
                    int_i = zeros(rydberg_states+1, rydberg_states+1)
                    int_j = zeros(rydberg_states+1, rydberg_states+1)
                    distance = 1
                    int_i[p+1, p+1] = c6[p, q]/distance
                    int_j[q+1, q+1] = c6[p, q]/distance
                    i == 1 ? h_int_temp = int_i : h_int_temp = id
                    for m in 2:n_qudits
                        m == i ? left_product = int_i : m == j ? left_product = int_j : left_product = id
                        h_int_temp = kron(left_product, h_int_temp)
                    end
                    h_int_total += h_int_temp
                end
            end
        end
    end
    return  drive + h_int_total
end

hamiltonian(detunings, rabis, c6, node_locations)