using LinearAlgebra, SparseArrays, ITensors, KrylovKit, Plots

# parameter initialisation
begin
    c6 = [
        5_420_503_000/(2pi)
    ] #= matrix c6{ij} for rydberg interaction coefficient between qudits i,j;
         diagonals are therefore the intra-, off-diagonals the inter-rydberg coefficients;
         units are GHz μm^6 =#

    rydberg_states = size(c6)[1] # no. of rydberg states used
    node_locations = [0 0 ; 1.75 0 ; 2*1.75 0 ; 3*1.75 0 ; 4*1.75 0] # location of the qudits (representing nodes of the graph) in units of μm

    evolve_time = 5e-6 # total evolution time in units of s
    n_steps = 300 # no. of timesteps
    Δ_max = [5].*((2pi)*1e6) # one detuning range for each rydberg state in units of GHz
    Δ = [LinRange(-1*(i^(1/3)),i^(1/3), n_steps).^3 for i in Δ_max] # Cubic sweep of over each detuning
    Ω_max = [1].*((2pi)*1e6) # one rabi frequency for between |g> and |r_i> for each rydberg state in units of GHz
    Ω = [i*ones(Int, n_steps) for i in Ω_max] # rabi frequency remains constant over sweep
    
    initial_state = [x > 1 ? 0 : x for x in 1:((rydberg_states+1)^size(node_locations)[1])] # ground state, all qudits |0>

end

function hamiltonian(Δ, Ω, c6, node_locations, t)
    """Generate total Hamiltonian of system using above parameters; sum of drive + interaction Hamiltonians"""
    id = 1 * Matrix{Float64}(I, rydberg_states+1, rydberg_states+1) # single-qudit identity matrix, dimension |g> + all |r_i>
    single = zeros(rydberg_states+1, rydberg_states+1)

    # populate single qubit hamiltonian
    for i in 1:rydberg_states
        single[i+1, i+1] = -Δ[i][t] 
        single[1, i+1] = 0.5*Ω[i][t]
        single[i+1, 1] = 0.5*Ω[i][t]
    end

    # generate placeholder matrix of total dimension of end product hamiltonian
    n_qudits = size(node_locations)[1]
    drive = zeros((rydberg_states+1)^n_qudits, (rydberg_states+1)^n_qudits)

    # tensor product sum of single qubit Hamiltonians
    for i in 1:n_qudits
        left_product = id
        drive_temp = id
        i == 1 ? drive_temp = single : drive_temp = id
        for m in 2:n_qudits
            m == i ? left_product = single : left_product = id
            drive_temp = kron(left_product, drive_temp)
        end
        drive += drive_temp
    end
    
    # placeholder matrix for interaction Hamiltonian
    dim = size(id)[1]^n_qudits
    h_int_total = zeros(dim, dim)

    # tensor product sum for interaction Hamiltonian: for every |r_p, r_q><r_p, r_q|(i,j) coefficient (i.e. matrix element)
    # generates a dim x dim matrix with that coefficient in the correct place; a sum then runs over every p,q (including q,p).
    # This procedure runs over every pair of qudits i,j. Each |r_p, r_q><r_p, r_q|(i,j) coefficient matrix is generated by the
    # square root of the coefficient value in the required location (and zeros elsewhere) replacing the identity matrix in the
    # positions i,j in the tensor product, i.e. I_1 * I_2 * |r_1><r_1|(3) * I_4 * |r_2><r_2|(5) * I_6 is the term in a six-qudit
    # setup for the intra-rydberg interaction between the rydberg states r_1 and r_2 between qudits 3 and 5; note there must
    # also be an additional term with r_1 and r_2 switched between the same qudits for these two rydberg states.
    for p in 1:rydberg_states
        for q in 1:rydberg_states
            for i in 1:n_qudits
                for j in i+1:n_qudits
                    h_int_temp = id
                    left_product = id
                    int_i = zeros(rydberg_states+1, rydberg_states+1)
                    int_j = zeros(rydberg_states+1, rydberg_states+1)
                    distance = sqrt((node_locations[i,1] - node_locations[j,1])^2 + ((node_locations[i,2] - node_locations[j,2])^2))
                    int_i[p+1, p+1] = sqrt(c6[p, q]/(distance^6))
                    int_j[q+1, q+1] = sqrt(c6[p, q]/(distance^6))
                    i == 1 ? h_int_temp = int_i : h_int_temp = id
                    for m in 2:n_qudits
                        m == i ? left_product = int_i : m == j ? left_product = int_j : left_product = id
                        h_int_temp = kron(left_product, h_int_temp)
                    end
                    h_int_total += h_int_temp
                end
            end
        end
    end
    return  drive + h_int_total
end

function total_hamiltonian()
    total_hamiltonian = zeros((rydberg_states+1)^size(node_locations)[1], (rydberg_states+1)^size(node_locations)[1], n_steps)
    for t in 1:n_steps
        total_hamiltonian[:,:,t] .= hamiltonian(Δ, Ω, c6, node_locations, t)[:,:]
    end
    return total_hamiltonian
end

function trotter_evolve(h_tot, initial_state)
    states = zeros(ComplexF64,(rydberg_states+1)^size(node_locations)[1], n_steps+1)
    states[:,1] = initial_state
    dt = evolve_time/n_steps
    for t in 1:n_steps
        h = h_tot[:,:,t] |> sparse
        psi = states[:,t] |> sparse
        states[:,t+1] = exponentiate(h, -im*dt, psi)[1]
    end
    return states
end

let
    states = trotter_evolve(total_hamiltonian(), initial_state)
    p = [real(dot(states[:,i], initial_state)*(dot(states[:,i], initial_state)')) for i in 1:size(states)[2]]
    plot([(i-1)*(evolve_time/n_steps) for i in 1:(n_steps+1)], p[:])
end

let
    states = trotter_evolve(total_hamiltonian(), initial_state)
    z2_state = [0, 1]
    for i in 1:(size(node_locations)[1]-1)
        i%2 == 1 ? left_product = [1, 0] : left_product = [0, 1]
        z2_state = kron(left_product, z2_state)
    end
    p = [real(dot(states[:,i], z2_state)*(dot(states[:,i], z2_state)')) for i in 1:size(states)[2]]
    plot([(i-1)*(evolve_time/n_steps) for i in 1:(n_steps+1)], p[:])

    state_space = zeros(size(initial_state)[1], size(initial_state)[1])
    for i in 1:size(initial_state)[1]
        state_space[i,i] = 1
    end
    p2 = [real(dot(states[:,301], state_space[i,:])*(dot(states[:,301], state_space[i,:])')) for i in 1:size(state_space)[1]]
    bar([i for i in 1:size(state_space)[1]], p2[:])

end