using LinearAlgebra, SparseArrays, ITensors, KrylovKit, Plots, ArnoldiMethod, LaTeXStrings, Expokit, FFTW, DSP

function hamiltonian(Δ, Ω, c6, node_locations, t)
    """Generate total Hamiltonian of system using above parameters; sum of drive + interaction Hamiltonians"""
    rydberg_states = size(c6)[1]
    n_qudits = size(node_locations)[1]
    id = 1 * Matrix{Float64}(I, rydberg_states+1, rydberg_states+1) # single-qudit identity matrix, dimension |g> + all |r_i>
    single = zeros(rydberg_states+1, rydberg_states+1, n_qudits)

    # populate single qubit hamiltonian
    for i in 1:rydberg_states
        for j in 1:n_qudits
            single[i+1, i+1, j] = -Δ[t, i, j]
            single[1, i+1, j] = 0.5*Ω[t, i, j]
            single[i+1, 1, j] = 0.5*Ω[t, i, j]
        end
    end

    # generate placeholder matrix of total dimension of end product hamiltonian
    drive = zeros((rydberg_states+1)^n_qudits, (rydberg_states+1)^n_qudits)

    # tensor product sum of single qubit Hamiltonians
    for i in 1:n_qudits
        left_product = id
        drive_temp = id
        i == 1 ? drive_temp = single[:,:,i] : drive_temp = id
        for m in 2:n_qudits
            m == i ? left_product = single[:,:,i] : left_product = id
            drive_temp = kron(left_product, drive_temp)
        end
        drive += drive_temp
    end
    
    # placeholder matrix for interaction Hamiltonian
    dim = size(id)[1]^n_qudits
    h_int_total = zeros(dim, dim)

    #= tensor product sum for interaction Hamiltonian: for every |r_p, r_q><r_p, r_q|(i,j) coefficient (i.e. matrix element)
    generates a dim x dim matrix with that coefficient in the correct place; a sum then runs over every p,q (including q,p).
    This procedure runs over every pair of qudits i,j. Each |r_p, r_q><r_p, r_q|(i,j) coefficient matrix is generated by the
    square root of the coefficient value in the required location (and zeros elsewhere) replacing the identity matrix in the
    positions i,j in the tensor product, i.e. I_1 * I_2 * |r_1><r_1|(3) * I_4 * |r_2><r_2|(5) * I_6 is the term in a six-qudit
    setup for the intra-rydberg interaction between the rydberg states r_1 and r_2 between qudits 3 and 5; note there must
    also be an additional term with r_1 and r_2 switched between the same qudits for these two rydberg states. =#
    for p in 1:rydberg_states
        for q in 1:rydberg_states
            for i in 1:n_qudits
                for j in 1:n_qudits
                    if i != j
                        h_int_temp = id
                        left_product = id
                        int_i = zeros(ComplexF64, rydberg_states+1, rydberg_states+1)
                        int_j = zeros(ComplexF64, rydberg_states+1, rydberg_states+1)
                        distance = sqrt((node_locations[i,1] - node_locations[j,1])^2 + ((node_locations[i,2] - node_locations[j,2])^2) + ((node_locations[i,3] - node_locations[j,3])^2))
                        int_i[p+1, p+1] = sqrt(complex(c6[p, q])/(distance^6))
                        int_j[q+1, q+1] = sqrt(complex(c6[p, q])/(distance^6))
                        i == 1 ? h_int_temp = int_i : j == 1 ? h_int_temp = int_j : h_int_temp = id
                        for m in 2:n_qudits
                            m == i ? left_product = int_i : m == j ? left_product = int_j : left_product = id
                            h_int_temp = kron(left_product, h_int_temp)
                        end
                        h_int_total += h_int_temp
                    end
                end
            end
        end
    end
    return  drive + h_int_total
end

function total_hamiltonian(n_steps)
    dim = size(hamiltonian(Δ, Ω, c6, node_locations, 1))[1]
    total_hamiltonian = zeros(ComplexF64, dim, dim, n_steps)
    for t in 1:n_steps
        total_hamiltonian[:,:,t] .= hamiltonian(Δ, Ω, c6, node_locations, t)[:,:]
    end
    return total_hamiltonian
end

function trotter_evolve(h_tot, initial_state, evolve_time)
    dim = size(h_tot)[1]
    n_steps = size(h_tot)[3]
    states = zeros(ComplexF64, dim, n_steps+1)
    states[:,1] = initial_state
    dt = evolve_time/n_steps
    for t in 1:n_steps
        h = h_tot[:,:,t] |> sparse
        psi = states[:,t]
        states[:,t+1] = expmv!(-im*dt, h, psi)
    end
    return states, h_tot
end

function partial_trace(density_matrix, rydberg_states, qudit_index)
    n_qudits = Int(log((rydberg_states+1), size(density_matrix)[1]))
    ones = zeros(rydberg_states+1, rydberg_states+1) .+ 1

    # generates set of matrices, with each matrix corresponding to each diagonal of the qudit to be summed over
    diagonal_markers = zeros(size(density_matrix)[1], size(density_matrix)[1], (rydberg_states+1))
    for i in 1:(rydberg_states+1)
        marker = zeros((rydberg_states+1), (rydberg_states+1))
        marker[i,i] = 1
        left_product = ones
        marked_temp = ones
        qudit_index == 1 ? marked_temp = marker : marked_temp = ones
        for i in 2:n_qudits
            i == qudit_index ? left_product = marker : left_product = ones
            marked_temp = kron(left_product, marked_temp)
        end
        diagonal_markers[:,:,i] = marked_temp
    end

    # rdm placeholder
    reduced_density_matrix = zeros(ComplexF64, (rydberg_states+1)^(n_qudits-1), (rydberg_states+1)^(n_qudits-1))

    # fills new reduced density matrix
    for k in eachindex(diagonal_markers[1,1,:])
        m = 1
        for i in eachindex(density_matrix[:,1])
            shift_m = false
            n = 1
            for j in eachindex(density_matrix[1,:])
                if diagonal_markers[i,j,k] != 0
                    reduced_density_matrix[m,n] += density_matrix[i,j]
                    n += 1
                    shift_m = true
                end
            end
            shift_m == true ? m += 1 : m += 0
        end
    end
    return reduced_density_matrix
end

function test_hermitian(h)
    h1 = h * h'
    h2 = h * h
    error_pairs = []
    for i in 1:size(h)[1]
        for j in i:size(h)[2]
            if !isequal(h1[i,j], h2[i,j]) && ((!isequal(abs(imag(h1[i,j])),0.0) && !isequal(abs(imag(h2[i,j])),0.0)) || !isequal(real(h1[i,j]), real(h2[i,j])))
                push!(error_pairs, [h1[i,j], h2[i,j]])
            end
        end
    end
    isempty(error_pairs)
end

# parameter initialisation for z2 crystal
begin
    c6 = [
        5_420_503_000
    ] #= matrix c6{ij} for rydberg interaction coefficient between qudits i,j;
         diagonals are therefore the intra-, off-diagonals the inter-rydberg coefficients;
         units are GHz μm^6 =#

    rydberg_states = size(c6)[1] # no. of rydberg states used

    evolve_time = (45.0e-6)*(21//20) # total evolution time in units of s
    n_steps = Int(400*(21//20)) # no. of timesteps

    Δ_max = [5 ; 5 ; 5 ; 5 ; 5 ; 5 ; 5].*((2pi)*1e6) # one detuning range for each rydberg state in units of GHz
    function Δ_sweep(Δ)
        sweep = zeros(n_steps)
        sweep[1:Int(n_steps*(1//42))] .= -1*Δ
        sweep[(Int(n_steps*(1//42))+1):Int(n_steps*(41//42))] .= (LinRange(-1*(Δ^(1/3)),Δ^(1/3), Int(n_steps*(20//21))).^3)
        sweep[(Int(n_steps*(41//42))+1):n_steps] .= Δ
        return sweep
    end

    Ω_max = [1 ; 1 ; 1 ; 1 ; 1 ; 1 ; 1].*((2pi)*1e6) # one rabi frequency for between |g> and |r_i> for each rydberg state in units of GHz
    function Ω_sweep(Ω)
        sweep = zeros(n_steps)
        sweep[1:Int(n_steps*(1//42))] .= LinRange(0, Ω, Int(n_steps*(1//42)))
        sweep[(Int(n_steps*(1//42))+1):Int(n_steps*(41//42))] .= Ω
        sweep[(Int(n_steps*(41//42))+1):n_steps] .= LinRange(Ω, 0, Int(n_steps*(1//42)))
        return sweep
    end

    
    blockade_radius = (c6[1]/Ω_max[1])^(1/6)
    lattice_spacing = 0.7*blockade_radius
    node_locations = [0 0 0 ; 1*lattice_spacing 0 0 ; 2*lattice_spacing 0 0 ; 3*lattice_spacing 0 0 ; 4*lattice_spacing 0 0 ; 5*lattice_spacing 0 0 ; 6*lattice_spacing 0 0] # location of the qudits (representing nodes of the graph) in units of μm

    Δ = zeros(n_steps, rydberg_states, size(node_locations)[1])
    Ω = zeros(n_steps, rydberg_states, size(node_locations)[1])
    for i in eachindex(Δ_max[1,:]), k in eachindex(Ω_max[1,:]) # loop over rydberg states
        for j in eachindex(Δ_max[:,1]), l in eachindex(Ω_max[:,1]) # loop over qudits
            for t in 1:n_steps
                Δ[t, i, j] = Δ_sweep(Δ_max[j, i])[t] # Cubic sweep of over each detuning
                Ω[t, k, l] = Ω_sweep(Ω_max[l, k])[t] # rabi frequency remains constant over sweep
            end
        end
    end

    initial_state = [x > 1 ? 0 : x for x in 1:((rydberg_states+1)^size(node_locations)[1])] # ground state, all qudits |0>
    
end

# data collection for z2 crystal
begin
    states, h_array = trotter_evolve(total_hamiltonian(n_steps), initial_state, evolve_time)
end

# ground state fidelity vs time
let
    p = [real(dot(states[:,i], initial_state)*(dot(states[:,i], initial_state)')) for i in 1:size(states)[2]]
    plot([(i-1)*(evolve_time/n_steps) for i in 1:(n_steps+1)], p[:])
end

# z2 crystal fidelity vs time, bar chart plot of fidelities
let
    z2_state = [0, 1]
    for i in 1:(size(node_locations)[1]-1)
        i%2 == 1 ? left_product = [1, 0] : left_product = [0, 1]
        z2_state = kron(left_product, z2_state)
    end
    p = [real(dot(states[:,i], z2_state)*(dot(states[:,i], z2_state)')) for i in 1:size(states)[2]]

    state_space = zeros(size(initial_state)[1], size(initial_state)[1])
    for i in 1:size(initial_state)[1]
        state_space[i,i] = 1
    end
    p2 = [real(dot(states[:,(n_steps+1)], state_space[i,:])*(dot(states[:,(n_steps+1)], state_space[i,:])')) for i in 1:size(state_space)[1]]
    bar([i for i in 1:size(state_space)[1]], p2[:])
    # plot([(i-1)*(evolve_time/n_steps) for i in 1:(n_steps+1)], p[:])
end

# eigenspectrum plot Krylov
let
    n_eig = 15
    eigenspectrum = zeros(Float64, n_eig, n_steps)
    for i in 1:(n_steps)
        h_sparse = h_array[:,:,i] |> sparse
        eigenvalues, eigenvectors, info = eigsolve(h_sparse, n_eig, :SR, tol=1e-12)
        eigenspectrum[:, i] = eigenvalues[1:n_eig]
    end
    plot(collect(1:n_steps), [eigenspectrum[i,:] for i in 1:n_eig])
end

# eigenspectrum plot Arnoldi
let
    n_eig = 20
    eigenspectrum = zeros(Float64, 15, n_steps)
    for i in 1:(n_steps)
        h_sparse = h_array[:,:,i] |> sparse
        decomps, history = partialschur(h_sparse, nev=n_eig, which=:SR, tol=1e-10)
        eigenvalues, eigenvectors = partialeigen(decomps)
        eigenspectrum[:, i] = real(eigenvalues[1:15])
    end
    plot(collect(1:n_steps), [eigenspectrum[i,:] for i in 1:15])
end

# colour plot of fidelity atom by atom
let 
    density_matrices = zeros(ComplexF64, size(states)[1], size(states)[1], size(states)[2])
    for i in eachindex(density_matrices[1,1,:])
        density_matrices[:,:,i] = kron(states[:,i], (states[:,i])')
    end
    n_qudits = size(node_locations)[1]
    
    reduced_density_matrices = zeros(ComplexF64, rydberg_states+1, rydberg_states+1, size(states)[2], n_qudits)

    for i in eachindex(density_matrices[1,1,:])
        for qudit in 1:n_qudits
            qudit_location = qudit
            reduced_matrix_temp = density_matrices[:,:,i]
            for m in 1:(n_qudits-1)
                if qudit_location != 1
                    reduced_matrix_temp = partial_trace(reduced_matrix_temp, rydberg_states, 1)
                    qudit_location -= 1
                else
                    reduced_matrix_temp = partial_trace(reduced_matrix_temp, rydberg_states, 2)
                end
            end
            reduced_density_matrices[:,:,i,qudit] = reduced_matrix_temp
        end
    end
    
    data = zeros(n_qudits, size(states)[2])
    for i in 1:n_qudits
        for j in eachindex(states[1,:])
            data[i,j] = Real(reduced_density_matrices[2,2,j,i])
        end
    end
    heatmap(data)
end

# z2 state fidelity vs length of time sweep
let 
    z2_state = [0, 1]
    for i in 1:(size(node_locations)[1]-1)
        i%2 == 1 ? left_product = [1, 0] : left_product = [0, 1]
        z2_state = kron(left_product, z2_state)
    end
    evolve_times = LinRange(35e-6, 50e-6, 10)
    fidelities = zeros(Float64, length(evolve_times))
    for i in eachindex(evolve_times)
        states, h_array = trotter_evolve(hamiltonian, initial_state, evolve_times[i])
        final_state = states[:,n_steps+1]
        fidelities[i] = real(dot(final_state, z2_state)*dot(final_state, z2_state)')
    end
    fidelities
    plot(evolve_times[:].*1e6, fidelities[:])
end

# parameter initialisation for 3 atom triangular graph, 2 Rydberg states; linear sweep
begin
    c6 = [
        361.0 -94.1;
        -94.1 862.7
    ] .* (2pi)*1e9 #= matrix c6{ij} for rydberg interaction coefficient between qudits i,j;
         diagonals are therefore the intra-, off-diagonals the inter-rydberg coefficients;
         units are GHz μm^6 =#

    rydberg_states = size(c6)[1] # no. of rydberg states used

    evolve_time = (8e-6)*(21//20) # total evolution time in units of s, factor same as for n_steps below
    n_steps = Int(400*(21//20)) # no. of timesteps x*y where x is no of timesteps for cubic sweep, y is factor for end bits

    Δ_max = [8 19 ; 8 19 ; 8 19].*((2pi)*1e6) # one detuning range for each rydberg state in units of GHz
    function Δ_sweep(Δ)
        sweep = zeros(n_steps)
        sweep[1:Int(n_steps*(1//42))] .= -1*Δ
        sweep[(Int(n_steps*(1//42))+1):Int(n_steps*(41//42))] .= (LinRange(-1*(Δ^(1)),Δ^(1), Int(n_steps*(20//21))))
        sweep[(Int(n_steps*(41//42))+1):n_steps] .= Δ
        return sweep
    end

    Ω_max = [3 7 ; 3 7 ; 3 7].*((2pi)*1e6) # one rabi frequency for between |g> and |r_i> for each rydberg state in units of GHz
    function Ω_sweep(Ω)
        sweep = zeros(n_steps)
        sweep[1:Int(n_steps*(1//42))] .= LinRange(0, Ω, Int(n_steps*(1//42)))
        sweep[(Int(n_steps*(1//42))+1):Int(n_steps*(41//42))] .= Ω
        sweep[(Int(n_steps*(41//42))+1):n_steps] .= LinRange(Ω, 0, Int(n_steps*(1//42)))
        return sweep
    end

    blockade_radius1 = (c6[1,1]/Ω_max[1])^(1/6)
	blockade_radius2 = (c6[2,2]/Ω_max[2])^(1/6)
    lattice_spacing = 0.7*blockade_radius1
    node_locations = [0 0 0 ; 0.5*lattice_spacing (sqrt(3)/2)*lattice_spacing 0 ; lattice_spacing 0 0 ] # location of the qudits (representing nodes of the graph) in units of μm

    Δ = zeros(n_steps, rydberg_states, size(node_locations)[1])
    Ω = zeros(n_steps, rydberg_states, size(node_locations)[1])
    for i in eachindex(Δ_max[1,:]), k in eachindex(Ω_max[1,:]) # loop over rydberg states
        for j in eachindex(Δ_max[:,1]), l in eachindex(Ω_max[:,1]) # loop over qudits
            for t in 1:n_steps
                Δ[t, i, j] = Δ_sweep(Δ_max[j, i])[t] # Cubic sweep of over each detuning
                Ω[t, k, l] = Ω_sweep(Ω_max[l, k])[t] # rabi frequency remains constant over sweep
            end
        end
    end
    
    initial_state = [x > 1 ? 0 : x for x in 1:((rydberg_states+1)^size(node_locations)[1])] # ground state, all qudits |0>

    ts = [(i-1)*(evolve_time/n_steps) for i in 1:(n_steps)]
    parameter_plot = plot(ts*1e6, Δ[:,1,2]./Δ_max[1,2])
    parameter_plot = plot!(ts*1e6, (Ω[:,1,2]./Ω_max[1,2]))
    plot(parameter_plot)
end

# data collection
begin
    states, h_array = trotter_evolve(total_hamiltonian(n_steps), initial_state, evolve_time)
end

# fidelity over a single timesweep
let 
    state_space = zeros(size(initial_state)[1], size(initial_state)[1])
    fidelities = zeros(n_steps+1)

    for i in 1:size(initial_state)[1]
        state_space[i,i] = 1
    end
    
    for j in 1:(n_steps+1)
        p2 = [real(dot(states[:,j], state_space[i,:])*(dot(states[:,j], state_space[i,:])')) for i in 1:size(state_space)[1]]
        fidelities[j] = p2[6] + p2[8] + p2[12] + p2[16] + p2[20] + p2[22]
    end
    plot(collect(1:(n_steps+1)), fidelities)
end

# fidelity vs timesweep length
let 
    times = LinRange(1e-7,5e-6, 200)*(21//20)
    fidelities = zeros(length(times))
    state_space = zeros(size(initial_state)[1], size(initial_state)[1])

    for i in 1:size(initial_state)[1]
        state_space[i,i] = 1
    end

    for i in eachindex(times)
        states, h_array = trotter_evolve(total_hamiltonian(n_steps), initial_state, times[i])
        final_state = states[:,(n_steps+1)]
        p2 = [real(dot(final_state, state_space[i,:])*(dot(final_state, state_space[i,:])')) for i in 1:size(state_space)[1]]
        fidelities[i] = p2[6] + p2[8] + p2[12] + p2[16] + p2[20] + p2[22]
    end
    plot(times*1e6, fidelities)
end

# parameter initialisation for a 6 atom triangular graph, 2 Rydberg states; cubic sweep
begin
    c6 = [
        361.0 -94.1;
        -94.1 862.7
    ] .* (2pi)*1e9
    # c6 = [
    #     361.0 -94.1 -35.0;
    #     -94.1 862.7 -226.7;
    #     -35.0 -226.7 1984.5
    # ] .* (2pi)*1e9 
        #= matrix c6{ij} for rydberg interaction coefficient between qudits i,j;
         diagonals are therefore the intra-, off-diagonals the inter-rydberg coefficients;
         units are GHz μm^6 =#

    rydberg_states = size(c6)[1] # no. of rydberg states used

    evolve_time = (8e-6)*(21//20) # total evolution time in units of s, factor same as for n_steps below
    n_steps = Int(400*(21//20)) # no. of timesteps x*y where x is no of timesteps for cubic sweep, y is factor for end bits

    Δ_max = [12 14 ; 12 14 ; 12 14 ; 12 14 ; 12 14 ; 12 14].*((2pi)*1e6) # one detuning range for each rydberg state in units of GHz
    function Δ_sweep(Δ)
        sweep = zeros(n_steps)
        sweep[1:Int(n_steps*(1//42))] .= -1*Δ
        sweep[(Int(n_steps*(1//42))+1):Int(n_steps*(41//42))] .= (LinRange(-1*(Δ^(1/3)),Δ^(1/3), Int(n_steps*(20//21)))).^3
        sweep[(Int(n_steps*(41//42))+1):n_steps] .= Δ
        return sweep
    end

    Ω_max = [3 7 ; 3 7 ; 3 7 ; 3 7 ; 3 7 ; 3 7].*((2pi)*1e6) # one rabi frequency for between |g> and |r_i> for each rydberg state in units of GHz
    function Ω_sweep(Ω)
        sweep = zeros(n_steps)
        sweep[1:Int(n_steps*(1//42))] .= LinRange(0, Ω, Int(n_steps*(1//42)))
        sweep[(Int(n_steps*(1//42))+1):Int(n_steps*(41//42))] .= Ω
        sweep[(Int(n_steps*(41//42))+1):n_steps] .= LinRange(Ω, 0, Int(n_steps*(1//42)))
        return sweep
    end

    blockade_radius1 = (c6[1,1]/Ω_max[1])^(1/6)
    lattice_spacing = 0.7*blockade_radius1
    node_locations = [0 0 0 ; 0.5*lattice_spacing (sqrt(3)/2)*lattice_spacing 0 ; lattice_spacing 0 0 ;
                        1*lattice_spacing sqrt(3)*lattice_spacing 0 ; 1.5*lattice_spacing (sqrt(3)/2)*lattice_spacing 0 ;
                        2*lattice_spacing 0 0]
                        # location of the qudits (representing nodes of the graph) in units of μm
    
    Δ = zeros(n_steps, rydberg_states, size(node_locations)[1])
    Ω = zeros(n_steps, rydberg_states, size(node_locations)[1])
    for i in eachindex(Δ_max[1,:]), k in eachindex(Ω_max[1,:]) # loop over rydberg states
        for j in eachindex(Δ_max[:,1]), l in eachindex(Ω_max[:,1]) # loop over qudits
            for t in 1:n_steps
                Δ[t, i, j] = Δ_sweep(Δ_max[j, i])[t] # Cubic sweep of over each detuning
                Ω[t, k, l] = Ω_sweep(Ω_max[l, k])[t] # rabi frequency remains constant over sweep
            end
        end
    end
    
    initial_state = [x > 1 ? 0 : x for x in 1:((rydberg_states+1)^size(node_locations)[1])] # ground state, all qudits |0>

    # ts = [(i-1)*(evolve_time/n_steps) for i in 1:(n_steps)]
    # parameter_plot = plot(ts*1e6, Δ[:,2]./Δ_max[2])
    # parameter_plot = plot!(ts*1e6, (Ω[:,2]./Ω_max[2]))
    # plot(parameter_plot)
end

# data collection
begin
    states, h_array = trotter_evolve(total_hamiltonian(n_steps), initial_state, evolve_time)
end

h = total_hamiltonian(n_steps)

# bar plot of states
let
    # z2_state = [0, 1]
    # for i in 1:(size(node_locations)[1]-1)
    #     i%2 == 1 ? left_product = [1, 0] : left_product = [0, 1]
    #     z2_state = kron(left_product, z2_state)
    # end
    # p = [real(dot(states[:,i], z2_state)*(dot(states[:,i], z2_state)')) for i in 1:size(states)[2]]

    state_space = zeros(size(initial_state)[1], size(initial_state)[1])
    for i in 1:size(initial_state)[1]
        state_space[i,i] = 1
    end
    p2 = [real(dot(states[:,(n_steps+1)], state_space[i,:])*(dot(states[:,(n_steps+1)], state_space[i,:])')) for i in 1:size(state_space)[1]]
    bar([i for i in 1:size(state_space)[1]], p2[:])
    # plot([(i-1)*(evolve_time/n_steps) for i in 1:(n_steps+1)], p[:])

end

# parameter initialisation for a 4 atom tetrahedral graph, 3 Rydberg states; cubic sweep
begin
    c6 = [
        361.0 -94.1 -35.0;
        -94.1 862.7 -226.7;
        -35.0 -226.7 1984.5
    ] .* (2pi)*1e9
        #= matrix c6{ij} for rydberg interaction coefficient between qudits i,j;
         diagonals are therefore the intra-, off-diagonals the inter-rydberg coefficients;
         units are GHz μm^6 =#

    rydberg_states = size(c6)[1] # no. of rydberg states used

    evolve_time = (8e-6)*(21//20) # total evolution time in units of s, factor same as for n_steps below
    n_steps = Int(400*(21//20)) # no. of timesteps x*y where x is no of timesteps for cubic sweep, y is factor for end bits

    Δ_max = [5 10 15 ; 5 10 15 ; 5 10 15 ; 5 10 15].*((2pi)*1e6) # one detuning range for each rydberg state in units of GHz
    function Δ_sweep(Δ)
        sweep = zeros(n_steps)
        sweep[1:Int(n_steps*(1//42))] .= -1*Δ
        sweep[(Int(n_steps*(1//42))+1):Int(n_steps*(41//42))] .= (LinRange(-1*(Δ^(1/3)),Δ^(1/3), Int(n_steps*(20//21)))).^3
        sweep[(Int(n_steps*(41//42))+1):n_steps] .= Δ
        return sweep
    end

    Ω_max = [1 2 5 ; 1 2 5 ; 1 2 5 ; 1 2 5].*((2pi)*1e6) # one rabi frequency for between |g> and |r_i> for each rydberg state in units of GHz
    function Ω_sweep(Ω)
        sweep = zeros(n_steps)
        sweep[1:Int(n_steps*(1//42))] .= LinRange(0, Ω, Int(n_steps*(1//42)))
        sweep[(Int(n_steps*(1//42))+1):Int(n_steps*(41//42))] .= Ω
        sweep[(Int(n_steps*(41//42))+1):n_steps] .= LinRange(Ω, 0, Int(n_steps*(1//42)))
        return sweep
    end

    blockade_radii = [(2*abs(c6[i,j])/(Ω_max[i]+Ω_max[j]))^(1/6) for i in eachindex(Ω_max),
                                                                     j in eachindex(Ω_max)]
    blockade_radius12 = (2*abs(c6[1,2])/(Ω_max[1]+Ω_max[2]))^(1/6)
    a = 0.74*blockade_radii[1,1]/sqrt(2)
    node_locations = [0 0 0 ; -a 0 a ; 0 a a ; -a a 0 ] # location of the qudits (representing nodes of the graph) in units of μm

    Δ = zeros(n_steps, rydberg_states, size(node_locations)[1])
    Ω = zeros(n_steps, rydberg_states, size(node_locations)[1])
    for i in eachindex(Δ_max[1,:]), k in eachindex(Ω_max[1,:]) # loop over rydberg states
        for j in eachindex(Δ_max[:,1]), l in eachindex(Ω_max[:,1]) # loop over qudits
            for t in 1:n_steps
                Δ[t, i, j] = Δ_sweep(Δ_max[j, i])[t] # Cubic sweep of over each detuning
                Ω[t, k, l] = Ω_sweep(Ω_max[l, k])[t] # rabi frequency remains constant over sweep
            end
        end
    end
    
    initial_state = [x > 1 ? 0 : x for x in 1:((rydberg_states+1)^size(node_locations)[1])] # ground state, all qudits |0>

    # ts = [(i-1)*(evolve_time/n_steps) for i in 1:(n_steps)]
    # parameter_plot = plot(ts*1e6, Δ[:,2]./(2pi))
    # parameter_plot = plot!(ts*1e6, (Ω[:,2]))
    # plot(parameter_plot)
end

# data collection
begin
    states, h_array = trotter_evolve(total_hamiltonian(n_steps), initial_state, evolve_time)
end

# bar plot of states
let
    states = trotter_evolve(total_hamiltonian(n_steps), initial_state, evolve_time)
    # z2_state = [0, 1]
    # for i in 1:(size(node_locations)[1]-1)
    #     i%2 == 1 ? left_product = [1, 0] : left_product = [0, 1]
    #     z2_state = kron(left_product, z2_state)
    # end
    # p = [real(dot(states[:,i], z2_state)*(dot(states[:,i], z2_state)')) for i in 1:size(states)[2]]

    state_space = zeros(size(initial_state)[1], size(initial_state)[1])
    for i in 1:size(initial_state)[1]
        state_space[i,i] = 1
    end
    p2 = [real(dot(states[:,(n_steps+1)], state_space[i,:])*(dot(states[:,(n_steps+1)], state_space[i,:])')) for i in 1:size(state_space)[1]]
    bar([i for i in 1:size(state_space)[1]], p2[:])
    # plot([(i-1)*(evolve_time/n_steps) for i in 1:(n_steps+1)], p[:])
    sum([p2[i] for i in eachindex(p2) if p2[i] > 0.04])
end

# parameter initialisation for 3 atom triangular graph, 2 Rydberg states; cubic sweep
begin
    c6 = [
        361.0 -94.1;
        -94.1 862.7
    ] .* (2pi)*1e9 #= matrix c6{ij} for rydberg interaction coefficient between qudits i,j;
         diagonals are therefore the intra-, off-diagonals the inter-rydberg coefficients;
         units are GHz μm^6 =#

    rydberg_states = size(c6)[1] # no. of rydberg states used

    evolve_time = (8e-6)*(21//20) # total evolution time in units of s, factor same as for n_steps below
    n_steps = Int(400*(21//20)) # no. of timesteps x*y where x is no of timesteps for cubic sweep, y is factor for end bits

    Δ_max = [8 19 ; 8 19; 8 19].*((2pi)*1e6) # one detuning range for each rydberg state in units of GHz
    function Δ_sweep(Δ)
        sweep = zeros(n_steps)
        sweep[1:Int(n_steps*(1//42))] .= -1*Δ
        sweep[(Int(n_steps*(1//42))+1):Int(n_steps*(41//42))] .= (LinRange(-1*(Δ^(1/3)),Δ^(1/3), Int(n_steps*(20//21))).^3)
        sweep[(Int(n_steps*(41//42))+1):n_steps] .= Δ
        return sweep
    end

    Ω_max = [3 7 ; 3 7 ; 3 7].*((2pi)*1e6) # one rabi frequency for between |g> and |r_i> for each rydberg state in units of GHz
    function Ω_sweep(Ω)
        sweep = zeros(n_steps)
        sweep[1:Int(n_steps*(1//42))] .= LinRange(0, Ω, Int(n_steps*(1//42)))
        sweep[(Int(n_steps*(1//42))+1):Int(n_steps*(41//42))] .= Ω
        sweep[(Int(n_steps*(41//42))+1):n_steps] .= LinRange(Ω, 0, Int(n_steps*(1//42)))
        return sweep
    end

    blockade_radius1 = (c6[1,1]/Ω_max[1])^(1/6)
	blockade_radius2 = (c6[2,2]/Ω_max[2])^(1/6)
    lattice_spacing = 0.7*blockade_radius1
    node_locations = [0 0 0 ; 0.5*lattice_spacing (sqrt(3)/2)*lattice_spacing 0 ; lattice_spacing 0 0 ] # location of the qudits (representing nodes of the graph) in units of μm

    Δ = zeros(n_steps, rydberg_states, size(node_locations)[1])
    Ω = zeros(n_steps, rydberg_states, size(node_locations)[1])
    for i in eachindex(Δ_max[1,:]), k in eachindex(Ω_max[1,:]) # loop over rydberg states
        for j in eachindex(Δ_max[:,1]), l in eachindex(Ω_max[:,1]) # loop over qudits
            for t in 1:n_steps
                Δ[t, i, j] = Δ_sweep(Δ_max[j, i])[t] # Cubic sweep of over each detuning
                Ω[t, k, l] = Ω_sweep(Ω_max[l, k])[t] # rabi frequency remains constant over sweep
            end
        end
    end
    
    initial_state = [x > 1 ? 0 : x for x in 1:((rydberg_states+1)^size(node_locations)[1])] # ground state, all qudits |0>

    # ts = [(i-1)*(evolve_time/n_steps) for i in 1:(n_steps)]
    # parameter_plot = plot(ts*1e6, Δ[:,1,2]./Δ_max[1,2])
    # parameter_plot = plot!(ts*1e6, (Ω[:,1,2]./Ω_max[1,2]))
    # plot(parameter_plot)
end

# data collection
begin
    states, h_array = trotter_evolve(total_hamiltonian(n_steps), initial_state, evolve_time)
end

# bar plot of state space fidelities
let 
    state_space = zeros(size(initial_state)[1], size(initial_state)[1])
    for i in 1:size(initial_state)[1]
        state_space[i,i] = 1
    end
    p2 = [real(dot(states[:,(n_steps+1)], state_space[i,:])*(dot(states[:,(n_steps+1)], state_space[i,:])')) for i in 1:size(state_space)[1]]
    bar([i for i in 1:size(state_space)[1]], p2[:])
    # p2[6] + p2[8] + p2[12] + p2[16] + p2[20] + p2[22]
end

# fidelity over a single timesweep
let
    state_space = zeros(size(initial_state)[1], size(initial_state)[1])
    fidelities = zeros(n_steps+1)

    for i in 1:size(initial_state)[1]
        state_space[i,i] = 1
    end
    
    for j in 1:(n_steps+1)
        p2 = [real(dot(states[:,j], state_space[i,:])*(dot(states[:,j], state_space[i,:])')) for i in 1:size(state_space)[1]]
        fidelities[j] = p2[6] + p2[8] + p2[12] + p2[16] + p2[20] + p2[22]
    end
    # plot(collect(1:(n_steps+1))[100:200], [(fidelities[100:200].-0.95).*20, (f.-0.99).*200, [cos(e_gap[i]*(8.4*i*1e-6/n_steps)) for i in 100:200]])
    plot(collect(1:(n_steps+1)), fidelities)
end

# symmetry breaking for 3 atom triangular graph, timesweep variations
begin
    n_offsets = 100
    n_timesweeps = 100
    fidelity_loss_points = zeros(n_offsets)
    fidelities_total = zeros(n_offsets, n_timesweeps)
    Δ_constraints = [(c6[i,i]/(lattice_spacing^6))-(Δ_max[1,i]) for i in eachindex(Δ_max[1,:])]
    # Δ_constraints = [-1*((c6[1,2]/(lattice_spacing^6))-(Δ_max[1,i])) for i in eachindex(Δ_max[1,:])]
    Δ_off = zeros(2, n_offsets)
    Δ_plot = zeros(n_offsets, n_steps)
    for i in eachindex(Δ_constraints)
        Δ_off[i, :] .= LinRange(0, Δ_constraints[i], n_offsets)
    end
    for k in eachindex(Δ_off[1, :])
        for l in eachindex(Δ_off[:, 1])
            Δ[:, l, 1] = Δ[:, l, 1] .+ Δ_off[l, k]
        end
        Δ_plot[k, :] = Δ[:, 1, 1]
        times = LinRange(1e-7,5e-6, n_timesweeps)*(21//20)
        fidelities = zeros(length(times))
        state_space = zeros(size(initial_state)[1], size(initial_state)[1])

        for i in 1:size(initial_state)[1]
            state_space[i,i] = 1
        end

        for i in eachindex(times)
            states, h_array = trotter_evolve(total_hamiltonian(n_steps), initial_state, times[i])
            final_state = states[:, (n_steps+1)]
            p2 = [real(dot(final_state, state_space[i,:])*(dot(final_state, state_space[i,:])')) for i in 1:size(state_space)[1]]
            fidelities[i] = p2[6] + p2[8] + p2[12] + p2[16] + p2[20] + p2[22]
        end

        found = false
        for i in eachindex(fidelities)
            if (fidelities[i] > 0.8) && (found == false)
                fidelity_loss_points[k] = i
                found = true
            end
        end
        fidelities_total[k, :] .= fidelities[:]
        for l in eachindex(Δ_off[:, 1])
            Δ[:, l, 1] = Δ[:, l, 1] .- Δ_off[l, k]
        end
    end
    plot(collect(1:n_offsets), fidelity_loss_points)
end

# symmetry breaking for 3 atom triangular graph, barchart heatmap
begin
    n_offsets = 100
    fidelities_total = zeros(n_offsets, size(initial_state)[1])
    Δ_constraints = [(c6[i,i]/(lattice_spacing^6))-(Δ_max[1,i]) for i in eachindex(Δ_max[1,:])]*5e-2
    # Δ_constraints = [-1*((c6[1,2]/(lattice_spacing^6))-(Δ_max[1,i])) for i in eachindex(Δ_max[1,:])]
    Δ_off = zeros(2, n_offsets)
    Δ_plot = zeros(n_offsets, n_steps)
    for i in eachindex(Δ_constraints)
        Δ_off[i, :] .= LinRange(0, Δ_constraints[i], n_offsets)
    end
    for k in eachindex(Δ_off[1, :])
        for l in eachindex(Δ_off[:, 1])
            Δ[:, l, 1] = Δ[:, l, 1] .+ Δ_off[l, k]
        end
        Δ_plot[k, :] = Δ[:, 1, 1]
        state_space = zeros(size(initial_state)[1], size(initial_state)[1])

        for i in 1:size(initial_state)[1]
            state_space[i,i] = 1
        end

        states, h_array = trotter_evolve(total_hamiltonian(n_steps), initial_state, 8.4e-6)
        final_state = states[:, (n_steps+1)]
        p2 = [real(dot(final_state, state_space[i,:])*(dot(final_state, state_space[i,:])')) for i in 1:size(state_space)[1]]

        fidelities_total[k, :] = p2[:]
        for l in eachindex(Δ_off[:, 1])
            Δ[:, l, 1] = Δ[:, l, 1] .- Δ_off[l, k]
        end
    end
    heatmap(fidelities_total)
end

# symmetry breaking for 6 atom triangular graph, timesweep variations
begin
    n_offsets = 10
    n_timesweeps = 10
    fidelity_loss_points = zeros(n_offsets)
    fidelities_total = zeros(n_offsets, n_timesweeps)
    Δ_constraints = [(c6[i,i]/(lattice_spacing^6))-(Δ_max[1,i]) for i in eachindex(Δ_max[1,:])]*1e-2
    # Δ_constraints = [-1*((c6[1,2]/(lattice_spacing^6))-(Δ_max[1,i])) for i in eachindex(Δ_max[1,:])]
    Δ_off = zeros(2, n_offsets)
    Δ_plot = zeros(n_offsets, n_steps)
    for i in eachindex(Δ_constraints)
        Δ_off[i, :] .= LinRange(0, Δ_constraints[i], n_offsets)
    end
    for k in eachindex(Δ_off[1, :])
        for l in eachindex(Δ_off[:, 1])
            Δ[:, l, 1] = Δ[:, l, 1] .+ Δ_off[l, k]
        end
        Δ_plot[k, :] = Δ[:, 1, 1]
        times = LinRange(1e-7,5e-6, n_timesweeps)*(21//20)
        fidelities = zeros(length(times))
        state_space = zeros(size(initial_state)[1], size(initial_state)[1])

        for i in 1:size(initial_state)[1]
            state_space[i,i] = 1
        end

        for i in eachindex(times)
            states, h_array = trotter_evolve(total_hamiltonian(n_steps), initial_state, times[i])
            final_state = states[:, (n_steps+1)]
            p2 = [real(dot(final_state, state_space[i,:])*(dot(final_state, state_space[i,:])')) for i in 1:size(state_space)[1]]
            fidelities[i] = p2[6] + p2[8] + p2[12] + p2[16] + p2[20] + p2[22]
        end

        found = false
        for i in eachindex(fidelities)
            if (fidelities[i] > 0.8) && (found == false)
                fidelity_loss_points[k] = i
                found = true
            end
        end
        fidelities_total[k, :] .= fidelities[:]
        for l in eachindex(Δ_off[:, 1])
            Δ[:, l, 1] = Δ[:, l, 1] .- Δ_off[l, k]
        end
    end
    plot(collect(1:n_offsets), fidelity_loss_points)
end

Δ_plot
Δ_off
fidelity_loss_points
fidelities_total
path = raw"C:\Users\Plowa\Programming\Projects\Durham\Project 2526\Figures\3 node triangular graph\3 node symmetry breaking\Fidelity vs duration graphs (linear negative)"
for i in 1:100
    plot(collect(1:size(fidelities_total)[2]), fidelities_total[i,:])
    savefig(joinpath(path, "3atom_symbreak_sweep_"*string(i)*".svg"))
end

# fidelity coloured eigenspectrum graph Krylov
begin
    n_offsets = 100
    Δ_constraints = [(c6[i,i]/(lattice_spacing^6))-(Δ_max[1,i]) for i in eachindex(Δ_max[1,:])].*1e-2
    Δ_off = zeros(2, n_offsets)
    n_eig = 15
    eig_fidelities = zeros(n_eig, n_steps)

    for i in eachindex(Δ_constraints)
        Δ_off[i, :] .= LinRange(0, Δ_constraints[i], n_offsets)
    end

    for l in eachindex(Δ_off[:, 80])
        Δ[:, l, 1] = Δ[:, l, 1] .+ Δ_off[l, 1]
    end

    states, h_array = trotter_evolve(total_hamiltonian(n_steps), initial_state, evolve_time)
    
    inst_eigvals = zeros(Float64, n_eig, n_steps)
    inst_eigvecs = zeros(ComplexF64, size(h_array)[1], n_eig, n_steps)
    for i in 1:(n_steps)
        h_sparse = h_array[:,:,i] |> sparse
        eigenvalues, eigenvectors, info = eigsolve(h_sparse, n_eig, :SR, tol=1e-10)
        inst_eigvals[:, i] = eigenvalues[1:n_eig]
        for j in 1:n_eig
            inst_eigvecs[:, j, i] = eigenvectors[j]
        end
    end
    
    for i in 1:n_steps
        for j in 1:n_eig
            eig_fidelities[j, i] = real(dot(inst_eigvecs[:, j, i], states[:, i])*dot(inst_eigvecs[:, j, i], states[:, i])')
        end
    end
end

# fidelity coloured eigenspectrum graph Arnoldi
begin
    n_offsets = 100
    Δ_constraints = [(c6[i,i]/(lattice_spacing^6))-(Δ_max[1,i]) for i in eachindex(Δ_max[1,:])]*7e-2
    Δ_off = zeros(2, n_offsets)
    n_eig = 15
    eig_fidelities = zeros(n_eig, n_steps)

    for i in eachindex(Δ_constraints)
        Δ_off[i, :] .= LinRange(0, Δ_constraints[i], n_offsets)
    end

    for l in eachindex(Δ_off[:, 100])
        Δ[:, l, 1] = Δ[:, l, 1] .+ Δ_off[l, 100]
    end

    states, h_array = trotter_evolve(total_hamiltonian(n_steps), initial_state, evolve_time)
    
    inst_eigvals = zeros(Float64, n_eig, n_steps)
    inst_eigvecs = zeros(ComplexF64, size(h_array)[1], n_eig, n_steps)
    for i in 1:(n_steps)
        h_sparse = h_array[:,:,i] |> sparse
        decomps, history = partialschur(h_sparse, nev=n_eig, which=:SR, tol=1e-10)
        eigenvalues, eigenvectors = partialeigen(decomps)
        inst_eigvals[:, i] = real(eigenvalues[1:n_eig])
        for j in 1:n_eig
            inst_eigvecs[:, j, i] = eigenvectors[:, j]
        end
    end
    
    for i in 1:n_steps
        for j in 1:n_eig
            eig_fidelities[j, i] = real(dot(inst_eigvecs[:, j, i], states[:, i])*dot(inst_eigvecs[:, j, i], states[:, i])')
        end
    end

    for l in eachindex(Δ_off[:, 80])
        Δ[:, l, 1] = Δ[:, l, 1] .- Δ_off[l, 80]
    end
end

p = plot(collect(1:(n_steps-2)), inst_eigvals[1, 1:(n_steps-2)], lc=cgrad(:default), line_z=eig_fidelities[1, 1:(n_steps-2)])
for i in 2:15
    p = plot!(collect(1:(n_steps-2)), inst_eigvals[i,1:(n_steps-2)], lc=cgrad(:default), line_z=eig_fidelities[i, (n_steps-2)])
end
display(p)

heatmap(eig_fidelities)

sum(eig_fidelities[1:6, n_steps])

eig_fidelities[:, 50]
plot(collect(1:n_steps), [eig_fidelities[i, :] for i in 1:n_eig], legend = :outerright)

e_gap = inst_eigvals[5, :] .- inst_eigvals[1, :]
plot(collect(1:n_steps), e_gap)
oscillation_period = (((e_gap./(2pi)).^(-1).*1e6))
plot(collect(1:(n_steps-15)), oscillation_period[1:(n_steps-15)])
plot(collect(1:(n_steps-15))[100:200], [cos(e_gap[i]*(8.4*i*1e-6/n_steps)) for i in 100:200])

eg = [abs(inst_eigvecs[i,1,n_steps-1]) > 0.01 ? (inst_eigvecs[i,1,n_steps-1]) : 0 for i in eachindex(inst_eigvecs[:,1,1])] |> sparse
fid = @.abs(eg).^2
s = 0
for i in findnz(fid)[1]
    s += fid[i]
end
s

(100*(8.4/420)/26)^(-1)*(2pi)
(26/100)/(2pi)

initial_state = inst_eigvecs[:, 1, 100]
f = zeros(101)
for i in 100:200
    f[i-99] = real(dot(initial_state, states[:, i])*dot(initial_state, states[:, i])')
end
fourier_real = real(fft(f))
fourier_imag = imag(fft(f))
rev = real(ifft(fft(f)))
plot(collect(109:200), [fourier_real[10:101], fourier_imag[10:101]])
plot(collect(100:200), [(f.-0.75).*100])
plot(collect(100:200), [(f), rev])
psd = periodogram(f)
psd.freq
plot(psd.freq[2:53], psd.power[2:53], xlabel="Frequency", ylabel="Power", title="Power Spectral Density")

begin
    Δ_constraints = [(c6[i,i]/(lattice_spacing^6))-(Δ_max[1,i]) for i in eachindex(Δ_max[1,:])].*1e-1
    Δ_off = zeros(2, n_offsets)

    for i in eachindex(Δ_constraints)
        Δ_off[i, :] .= LinRange(0, Δ_constraints[i], n_offsets)
    end

    for l in eachindex(Δ_off[:, 80])
        Δ[:, l, 1] = Δ[:, l, 1] .- Δ_off[l, 80]
    end

    times = LinRange(1e-7,5e-6, 300)*(21//20)
    fidelities_perturbed = zeros(length(times))
    state_space = zeros(size(initial_state)[1], size(initial_state)[1])

    for i in 1:size(initial_state)[1]
        state_space[i,i] = 1
    end

    for i in eachindex(times)
        states, h_array = trotter_evolve(total_hamiltonian(n_steps), initial_state, times[i])
        final_state = states[:,(n_steps+1)]
        p2 = [real(dot(final_state, state_space[i,:])*(dot(final_state, state_space[i,:])')) for i in 1:size(state_space)[1]]
        fidelities_perturbed[i] = p2[6] + p2[8] + p2[12] + p2[16] + p2[20] + p2[22]
    end

    for l in eachindex(Δ_off[:, 80])
        Δ[:, l, 1] = Δ[:, l, 1] .+ Δ_off[l, 80]
    end
end

begin 
    times = LinRange(1e-7,5e-6, 300)*(21//20)
    fidelities = zeros(length(times))
    state_space = zeros(size(initial_state)[1], size(initial_state)[1])

    for i in 1:size(initial_state)[1]
        state_space[i,i] = 1
    end

    for i in eachindex(times)
        states, h_array = trotter_evolve(total_hamiltonian(n_steps), initial_state, times[i])
        final_state = states[:,(n_steps+1)]
        p2 = [real(dot(final_state, state_space[i,:])*(dot(final_state, state_space[i,:])')) for i in 1:size(state_space)[1]]
        fidelities[i] = p2[6] + p2[8] + p2[12] + p2[16] + p2[20] + p2[22]
    end
end

1/(5.6)

plot(times*1e6, fidelities_perturbed, label=L"$\Delta_{off} < 0$")
plot!(times*1e6, fidelities, label=L"$\Delta_{off} = 0$")
plot!(times*1e6, fidelities_perturbed_pos, label=L"$\Delta_{off} > 0$")